package br.com.liape.sistemaGerenciamento.constantes;

public enum FlagsLogAcao {
	CADASTRO_ANO_SEMESTRE(0),
	REMOVER_ANO_SEMESTRE(1),
	ATUALIZAR_ANO_SEMESTRE(2),
	CADASTRAR_CURSO(3),
	REMOVER_CURSO(4),
	ATUALIZAR_CURSO(5),
	CADASTRAR_DISCIPLINA(6),
	REMOVER_DISCIPLINA(7),
	ATUALIZAR_DISCIPLINA(8),
	CADASTRAR_ESCALA(9),
	REMOVER_ESCALA(10),
	ATUALIZAR_ESCALA(11),
	CADASTRAR_FOTOPERFIL(12),
	REMOVER_FOTOPERFIL(13),
	ATUALIZAR_FOTOPERFIL(14),
	CADASTRAR_GRUPO(15),
	REMOVER_GRUPO(16),
	ATUALIZAR_GRUPO(17),
	LOGAR_USUARIO(18),
	CADASTRAR_MENSAGEM(19),
	REMOVER_ENTRADA_MENSAGEM(20),
	REMOVER_ENVIADO_MENSAGEM(21),
	ATUALIZAR_MENSAGEM(22),
	VISUALIZAR_MENSAGEM(23),
	CADASTRAR_SEMESTRAL(24),
	REMOVER_SEMESTRAL(25),
	ATUALIZAR_SEMESTRAL(26),
	CADASTRAR_EXPORADICO(27),
	REMOVER_EXPORADICO(28),
	ATUALIZAR_EXPORADICO(29),
	CADASTRAR_SALA(30),
	REMOVER_SALA(31),
	ATUALIZAR_SALA(32),
	REMOVER_ORDEM(33),
	FINAlIZAR_ORDEM(34),
	CADASTRAR_ORDEM_SALA(35),
	REMOVER_ORDEM_SALA(36),
	ATUALIZAR_ORDEM_SALA(37),
	CADASTRAR_ORDEM_COMPUTADOR(38),
	REMOVER_ORDEM_COMPUTADOR(39),
	ATUALIZAR_ORDEM_COMPUTADOR(40),
	CADASTRAR_SUBORDEM_TURNO(41),
	REMOVER_SUBORDEM_TURNO(42),
	ATUALIZAR_SUBORDEM_TURNO(43),
	CADASTRAR_SUBORDEM_USUARIO(44),
	REMOVER_SUBORDEM_USUARIO(45),
	ATUALIZAR_SUBORDEM_USUARIO(46),
	VISUALIZAR_SUBORDEM(47),
	REDIRECIONAR_SUBORDEM(48),
	FINALIZAR_SUBORDEM(49),
	CADASTRAR_PROFESSOR(50),
	REMOVER_PROFESSOR(51),
	ATUALIZAR_PROFESSOR(52),
	CADASTRAR_TURNO(53),
	REMOVER_TURNO(54),
	ATUALIZAR_TURNO(55),
	CADASTRAR_USUARIO_TURNO(56),
	REMOVER_USUARIO_TURNO(57),
	ATUALIZAR_USUARIO_TURNO(58),
	CADASTRAR_USUARIO(59),
	REMOVER_USUARIO(60),
	ATUALIZAR_USUARIO(61),
	CADASTRAR_ARQUIVO(62),
	REMOVER_ARQUIVO(63),
	ATUALIZAR_ARQUIVO(64),
	CADASTRAR_USUARIOAD(65),
	DELETAR_USUARIOAD(66),
	VERIFICAR_USUARIOAD(67),
	RESETAR_SENHA_USUARIOAD(68);
	
	private int codigo;
	
	private FlagsLogAcao(int codigo) {
		this.codigo = codigo;
	}
	
	public int getCodigo() {
		return codigo;
	}
	
	public void setCodigo(int codigo) {
		this.codigo = codigo;
	}
	
}
